#pipeline time
pr:
  branches:
    include:
    - '*'
trigger:
  branches:
    include:
    - master

steps:
- task: AzureCLI@2
  displayName: 'Infra Deploy'
  inputs:
    azureSubscription: 'azureprod'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: az deployment group create -g rg-networking -f ./main.bicep
