#pipeline time
pr:
  branches:
    include:
    - '*'
trigger:
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Infra Deploy'
  inputs:
    azureSubscription: 'prod'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: az deployment group create -g rg-networking -f $(Pipeline.Workspace)/main.bicep
